import './globals.css'
import Image from "next/image"
import stackOverflow from "./assets/stackoverflow.svg"
import type { Metadata } from 'next'
import { Ubuntu } from 'next/font/google'
import PostContext from "./contexts/PostContext"
import CompStateContext from "./contexts/ComponentStateContext"
import StatusMessageContext from "./contexts/StatusMessageContext"
import Header from './components/Header'

const font = Ubuntu({ subsets: ['latin'], weight: ["400", "700", "500"] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <StatusMessageContext>
          <CompStateContext>
            <Header />
            <main>
              <PostContext>
                {children}
              </PostContext>
            </main>
          </CompStateContext>
        </StatusMessageContext>
      </body>
    </html>
  )
}
